version: '3'

services:
    database:
        image: mariadb
        restart: always
        environment: 
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: emaildatabase
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - data:/var/lib/mysql
volumes:
    data:
